name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: actions/docker/cli@v2
      with:
        args: build -t nayantara52/nayan-docker-images:latest .

    - name: Docker Login
      uses: actions/docker/login@v2
      with:
        username: nayantara52
        password: Vkssann@2805

    - name: Push Docker Image to Docker Hub
      uses: actions/docker/cli@v2
      with:
        args: push nayantara52/nayan-docker-images:latest

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIARWAZI6BRA2BMG36N
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no new-ec2-user@ec2-18-220-87-179.us-east-2.compute.amazonaws.com "docker pull nayantara52/nayan-docker-images:latest && docker run -d -p 80:80 nayantara52/nayan-docker-images:latest"



    

  


