name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: pre-production

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Configure Docker credentials
      uses: docker-actions/configure-docker-credentials@v1
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the docker image
      uses: docker-actions/build-push@v2
      with:
        context: .
        push: true
        tags: nayantara52/nayan-docker-images:version1

    - name: Login/deploy to Amazon EC2
      uses: aws-actions/amazon-ec2-login@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY}}
        script: |
          docker stop nayan-docker-images || true
          docker rm nayan-docker-images || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/nayan-docker-images:version1
          docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/nayan-docker-images:version1


    

  


