name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: na
        password: na

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nayantara52/nayan-docker-images:latest 

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: na
        aws-secret-access-key: na
        aws-region: us-east-2

    - name: pull image to ec2
      run: |
        docker pull nayantara52/nayan-docker-images:latest 

    - name: run image
      run: |
        docker run -d -p 80:80 nayantara52/nayan-docker-images:latest



    

  


