name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Configure Docker credentials
      uses: docker/login-action@v1
      with:
        docker_username: nayantara52
        docker_password: Vkssann@2805

    - name: Build and push the docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nayantara52/nayan-docker-images:version1

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIARWAZI6BRA2BMG36N
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no new-ec2-user@ec2-18-220-87-179.us-east-2.compute.amazonaws.com "docker pull nayantara52/nayan-docker-images:version1 && docker run -d -p 80:80 nayantara52/nayan-docker-images:version1"



    

  


